### ISSUE TITLE
cmd.run with pipes will not work

### ISSUE THREAD

**Issue by x12a1f** [mariodpros/ufw-formula#4]
In https://github.com/mariodpros/ufw-formula/blob/master/_modules/ufw.py#L6 cmd.run is used with a command containing pipes. 

There is a warning about this in the docs:

> This means that any shell-specific functionality such as 'echo' or the use of pipes, redirection or &&,  should either be migrated to cmd.shell or have the python_shell=True flag set here.

**Comment by mariodpros** [comment]
@ralphvanetten thanks for the bug report.
